### ISSUE TITLE
Got an error trying to tag a talk with "javascript"

### ISSUE THREAD

**Issue by andreamiddleton** [imath/wordcamp-talks#13]
Submitted one talk called "Learn Javascript Deeply" which was tagged "Javascript".

Then I submitted a second talk (same browser session) called "The Sneaky Snacky Squirrel Game" and when I tried to tag it "javascript" too, I got this error:
<img width="1072" alt="screen shot 2016-11-30 at 2 45 31 pm" src="https://cloud.githubusercontent.com/assets/2285933/20774653/19d321f0-b70c-11e6-816a-5d3243617a23.png">

If the settings prohibit someone from tagging multiple talks with the same tag, we should change those settings. :)

**Comment by imath** [comment]
Good catch, i was able to reproduce. I agree. Thanks for your feedback.
