### ISSUE TITLE
Pending submissions can be rated

### ISSUE THREAD

**Issue by tomjn** [imath/wordcamp-talks#15]
A talk can be rated as great or terrible during the pending stage, the rating UI should be hidden until after the talk has been given

**Comment by imath** [comment]
The rating UI is used to help select the talk and is never showed to the speaker.

Comments and rates are only available for admins/jurors/raters.

+ blind raters only see their votes ?

I'm not sure to understand what's wrong actually :)

**Comment by tomjn** [comment]
Ah perhaps my admin status was giving me special access :)
