### ISSUE TITLE
Q: Post Status and the Publish box

### ISSUE THREAD

**Issue by tomjn** [imath/wordcamp-talks#17]
Currently there is a metabox titled Workflow with pending/selected/shortlisted/rejected, then a publish box with the post already published and marked as privately published.

Would it not make more sense to use custom post statuses and reuse the existing pending status, and remove/adjust the publish box? This would give the correct filters at the top of the admin edit screen and simplify filtering

**Comment by imath** [comment]
The private status guarantees only admins/raters/blind raters can do the selection without the speaker to see rates/comments.

The private status also guarantees only speakers will see their own talk. So the post status is used by the plugin as a privacy thing.

The plugin was first designed as a front end submission tool. Speakers could come back and submit new talks while jurors could "secretly" evaluate talks thanks to this private status.

The other meta thing was to easily extract selected talks.

But if you think it's the wrong approach, i'm fine with any improvements :)
