### ISSUE TITLE
Widgets?

### ISSUE THREAD

**Issue by jennybeaumont** [imath/wordcamp-talks#24]
Discussing widgets, we think they can be deleted.
Of the 5 widgets, only 2 have valuable navigation features:
- Talk categories
- Recents comments

The downside of widgets is that they would be visible to everyone - even logged out users.
We think it'd be better to remove all as widgets, then eventually revisit adding back any navigation features that could improve the experience directly in the templates.

Thoughts?

**Comment by iandunn** [comment]
+1

**Comment by tomjn** [comment]
Does this include the WC Talks Nav widget? The rest I can see being removed, else we'd need to manually add nav menu items for each entry along with making sure it made sense for logged out and logged in users
