### ISSUE TITLE
Prefix Custom Role Names

### ISSUE THREAD

**Issue by iandunn** [imath/wordcamp-talks#27]
Currently the custom roles are a bit hard to distinguish from Core roles in a dropdown. They could also be confusing to admins who don't use the plugin.

![screen shot 2017-01-25 at 11 40 45 am](https://cloud.githubusercontent.com/assets/484068/22306236/55b1faee-e2f3-11e6-897a-4e4b63b6e4be.png)

I wonder if it'd make things more clear/usable if they were all prefixed? e.g., something like 'Talks: Juror`, `Talks - Speaker`, etc.

Even if we all agree this would be helpful, it'd definitely be a low priority. This can be closed if roles are removed in #26.

**Comment by tomjn** [comment]
Agreed, this could be confusing, I also wonder if the speaker role is necessary now that we know a user doesn't have to have a role to be logged into a site? @imath perhaps you can weigh in on the necessary changes for the speaker role to be removed. The other changes should be a trivial text change

**Comment by imath** [comment]
@tomjn The speaker role is not generated by WordCamp talks because it doesn't make any sense.

The only roles generated by WordCamp talks are Juror, Rater and blind rater.

I guess the speaker role has been added by another plugin on @iandunn screencapture.

About prefixing, let's wait to see what happens with #26 :)

**Comment by iandunn** [comment]
> The speaker role is not generated by WordCamp talks

Ah, you're right, I think that's left over from an old patch that never got committed.

**Comment by jennybeaumont** [comment]
Are we still suggesting to prefix the 3 Talk Proposal related roles? Or can I close this out?

**Comment by jennybeaumont** [comment]
I'm closing this out for now.

**Comment by iandunn** [comment]
> Are we still suggesting to prefix the 3 Talk Proposal related roles? Or can I close this out?

That's right, so `Juror`, `Rater`, and `Blind Rater`, would become something like `Talks: Juror`, `Talks: Rater`, and `Talks: Blind Rater`.
