### ISSUE TITLE
Specific fields in the Talk submit form

### ISSUE THREAD

**Issue by imath** [imath/wordcamp-talks#5]
Previously in this file  https://github.com/imath/wc-talk/blob/master/WP_PLUGIN_DIR/wp-idea-stream-custom.php we were using custom fields to eventually add targeted audience, or the kind of talk.

The WP Idea Stream custom fields API is also in this plugin, but i think it's quite complex to use as it requires a mu-plugins/functions or a theme function to register them.

I think it would be more interesting to use the talks category taxonomy and benefit from its hierarchical feature. This way, we could create as many parent categories as needed and easily filter the talks stream according to it. The Talks form would display parent category + description and their child categories.

It would look like this:

Targeted audience (parent category)
[] developer (child category)  
[] designer (child category)  
[] random audience (child category) 

etc.. More flexible imho as the edit-tags UI is very easy to use. Any objections @jennybeaumont ?

**Comment by jennybeaumont** [comment]
Makes sense +1
