### ISSUE TITLE
Registration flow

### ISSUE THREAD

**Issue by andreamiddleton** [imath/wordcamp-talks#7]
After signing up, I got this screen: 
<img width="1048" alt="screen shot 2016-11-28 at 3 17 11 pm" src="https://cloud.githubusercontent.com/assets/2285933/20690535/0d7de1b6-b580-11e6-8993-77c977a627c6.png">
I wasn't sure how to add my talk, because I hadn't gotten my confirmation email yet. It would be better if the message were something like "A confirmation email with login information is on its way! Log in with that information to submit a talk!" 
Even better would be to automatically log me in when I submit my information, if that's possible. :)

**Comment by imath** [comment]
Thanks a lot for your feedback.

There's actually a feedback message but it's not showing on the Test Drive. The feedback feature is using cookies to persist after a redirect just like BuddyPress does (the inspiration source of it!) But i think this issue shows we cannot rely on it at 100% ;)

So the first thing i'll do is to choose another way to deal with feedbacks when redirecting the user.

About automatically log the user in, i'd usually argue the account activation email is a way to check the email validity, but i agree for WordCamp talks, as the post type is privately published, it can be interesting to make things easier and redirect the user automagically logged in to the Talk submit form. So i will add an option to let the Site Administrator decide what's best for his specific event.

Thanks for your feedback, working on this 2 improvements. I'll update the issue when i'll make progress on it.

**Comment by imath** [comment]
f3d9967 introduced a new way to manage user feedbacks, for this particular case, we should see this:

![regular](https://cloud.githubusercontent.com/assets/1834524/20748627/3b32fbf8-b6ef-11e6-86b9-502ce292ec04.png)

I'm about to commit the Autolog feature. There will be an option into the Talks settings Administration screen to enable it. By default it will be disabled. If the feature is on, the "just signed up user" will be redirected to the submit form and a feedback message will inform him he should have received an email to set his password later as shown below:

![autolog](https://cloud.githubusercontent.com/assets/1834524/20749147/6650e28a-b6f1-11e6-9190-6ffda55686bb.png)
